__author__ = "Hanna Soderstrom"
__copyright__ = "Copyright 2023, Hanna Soderstrom"
__email__ = "hanna.soderstrom@gu.se"
__license__ = "GPL-3"

include: "rules/common.smk"
#include: "rules/sentieon.smk"

#report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),


module sentieon:
    snakefile:
        github(
            "hydra-genetics/sentieon",
            path="workflow/Snakefile",
            tag=config["modules"]["sentieon"],
        )
    config:
        config


use rule * from sentieon as sentieon_*


module prealignment:
    snakefile:
        github(
            "hydra-genetics/prealignment",
            path="workflow/Snakefile",
            tag=config["modules"]["prealignment"],
        )
    config:
        config


use rule * from prealignment as prealignment_*
